### PR TITLE
Feature/character details

### PR DESCRIPTION
**Pull request by kevinhuynh269**
Added some tests for activated routes

### CODE REVIEW

**Comment by arthuranteater** [comment]
a few merge conflicts to resolve

**Review by LWooler — APPROVED** [review]
Looks good to me, well done, just needs merges resolved

**Comment by rmuehler** [comment]
Looks good.

**Comment by 100xlongx** [comment]
conflicts resolved

**Comment by psalaza** [comment]
hoorah!

**Review by mosdevly — CHANGES_REQUESTED** [review]
You've got a failing test to fix!

edit: Actually, this seems to be related to a recent commit.
It looks last commit that apparently is part of the current error:
https://github.com/Tech-Student-Labs/swapi-client-ts/runs/2494690142?check_suite_focus=true#step:4:53

I'll investigate and see what we can find out.

**Comment by mosdevly** [comment]
Go ahead and pull the updates and lets see if the fix helps.

**Comment by wangscs** [comment]
PR#12 passed with the fix so ¯\_(ツ)_/¯

**Comment by mosdevly** [comment]
It did, but the bug is still from your feature branch unfortunately :( Find out which tests are causing this issue and isolate them for now. You can remove it and push your code without it @wangscs

**Review by mosdevly — APPROVED** [review]

**Pull request merged**
